### PR TITLE
ignore field by regexp

### PR DESCRIPTION
**Pull request by Eomm**
As described in this issue https://github.com/thedgmbh/mongoose-dummy/issues/2 I have implemented the possibility to add a regexp object to the `ignore` array parameter.

### CODE REVIEW

**Comment by Eomm** [comment]
Hello @ahmed-agiza,
did you see this PR? What do you think?

Thank you

**Comment by gundour** [comment]
Hi @Eomm,
I am the current maintainer for this package, I checked this PR and I think it is a good addition to the module.

Thanks for your contribution.

**Comment by Eomm** [comment]
I hope you shall distribute it then 😄 

Thank to you

**Comment by Eomm** [comment]
@gundour What is the process now for get this function on the official release?

Thks

**Pull request merged**
